### ISSUE TITLE
[Get] Support for getting all entries for Vlan/Neighbor/Vrf

### ISSUE THREAD

**Issue by prsunny** [sonic-net/sonic-restapi#102]
Expose a /all version of the following methods

 1. Vlan Neighbor: /config/interface/vlan/{vlan_id}/neighbor. No dependency
 2. Vlan member: /config/interface/vlan/{vlan_id}/member. No dependency
 3. VLAN: /config/interface/vlan Depends on 2(VNET). Dependes on successful deletion on all child elements 2(Vlan Neighbor) and 3(Vlan member)
 4. Vrouter/VNET: /config/vrouter/{vnet_id}. Depends on successful deletion of all child elements 4(Vlan) and 1(Routes)

**Comment by sumukhatv** [comment]
https://github.com/sonic-net/sonic-restapi/pull/106
